entries:
  - env: DEV
    product: PUBLIC_ENERGY_ANALYTICS
    username: gschumacher2
    function: ADMIN
  - env: DEV
    product: PUBLIC_ENERGY_ANALYTICS
    username: dkelley
    function: ADMIN
  - env: QA
    product: PUBLIC_ENERGY_ANALYTICS
    username: gschumacher2
    function: ADMIN
  - env: QA
    product: PUBLIC_ENERGY_ANALYTICS
    username: dkelley
    function: ADMIN
  - env: PROD
    product: PUBLIC_ENERGY_ANALYTICS
    username: gschumacher2
    function: ADMIN
  - env: PROD
    product: PUBLIC_ENERGY_ANALYTICS
    username: dkelley
    function: ADMIN
